#!/bin/sh

set -eu

# run static code checks like pyflakes and pep8
PYEXEFILES="$(git grep -lI '^#!.*python') $(git ls-files "*.py")"
flake8 $PYEXEFILES

mypy --no-error-summary --ignore-missing-imports --scripts-are-modules .

./test-bots
